import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Env loading, most specific first:
 *   1. variables already exported in the environment
 *   2. .env.<role>  — this process's own file, when it has a role
 *   3. .env.local   (generated by `npm run seed` — holds this machine's deployed
 *      address and throwaway database)
 *   4. .env         (edited by hand)
 *
 * The role file is what lets two verifiers on one machine differ without either
 * one editing the shared file: its own signing key, its own COMPUTE_API_KEY and
 * Payment Layer deposit, its own thresholds. A verifier operator pays for its
 * own inference, so "its own key" is the normal case, not an edge one.
 *
 * The role comes from `PROOFRELAY_ROLE`, or from `VERIFIER_PROFILE` when a
 * verifier worker sets it — `VERIFIER_PROFILE=a` reads `.env.verifier-a`.
 *
 * .env.local winning over .env is deliberate, and it is also the single most
 * common way a service ends up talking to the wrong chain, so `resolvedFrom()`
 * reports which file every value came from and the API prints it on startup.
 */

const ORIGINS = new Map<string, string>();

export function repoRoot(): string {
  // packages/config/dist/env.js -> repo root is three levels up.
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 6; i += 1) {
    if (existsSync(resolve(dir, "package.json"))) {
      const pkg = JSON.parse(readFileSync(resolve(dir, "package.json"), "utf8"));
      if (pkg.name === "proofrelay") return dir;
    }
    dir = dirname(dir);
  }
  return process.cwd();
}

function parseDotenv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

/** `.env.<role>` for this process, or null when it has no role. */
function roleEnvFile(): string | null {
  const explicit = process.env.PROOFRELAY_ROLE?.trim();
  if (explicit) return `.env.${explicit}`;
  const profile = process.env.VERIFIER_PROFILE?.trim();
  if (profile) return `.env.verifier-${profile.toLowerCase()}`;
  return null;
}

let loaded = false;

export function loadEnv(root = repoRoot()): void {
  if (loaded) return;
  loaded = true;
  for (const key of Object.keys(process.env)) ORIGINS.set(key, "environment");

  for (const file of [roleEnvFile(), ".env.local", ".env"].filter((f): f is string => f !== null)) {
    const path = resolve(root, file);
    if (!existsSync(path)) continue;
    const values = parseDotenv(readFileSync(path, "utf8"));
    for (const [key, value] of Object.entries(values)) {
      if (process.env[key] !== undefined) continue;
      process.env[key] = value;
      ORIGINS.set(key, file);
    }
  }
}

export function resolvedFrom(key: string): string {
  return ORIGINS.get(key) ?? "default";
}

export function env(key: string): string | undefined {
  loadEnv();
  const value = process.env[key];
  return value === undefined || value === "" ? undefined : value;
}

export function requireEnv(key: string): string {
  const value = env(key);
  if (value === undefined) throw new Error(`${key} is not set`);
  return value;
}

export function envInt(key: string, fallback: number): number {
  const value = env(key);
  if (value === undefined) return fallback;
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed)) throw new Error(`${key} must be an integer, got ${value}`);
  return parsed;
}

export function envBool(key: string, fallback: boolean): boolean {
  const value = env(key);
  if (value === undefined) return fallback;
  return /^(1|true|yes|on)$/i.test(value);
}

export function envList(key: string, fallback: string[] = []): string[] {
  const value = env(key);
  if (value === undefined) return fallback;
  return value
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean);
}
